apiVersion: v2
name: kubeguardian
description: Automated Kubernetes Self-Healing & Auto-Remediation Tool
type: application
version: 1.1.0
appVersion: "1.1.0"
home: https://github.com/NotHarshhaa/kubeguardian
sources:
  - https://github.com/NotHarshhaa/kubeguardian
maintainers:
  - name: KubeGuardian Team
    email: team@kubeguardian.io
keywords:
  - kubernetes
  - monitoring
  - remediation
  - self-healing
  - automation
  - devops
  - sre
annotations:
  category: Infrastructure
  licenses: Apache-2.0
dependencies: []
icon: https://raw.githubusercontent.com/tandpfun/skill-icons/65dea6c4eaca7da319e552c09f4cf5a9a8dab2c8/icons/Kubernetes.svg
