{{/*
Secret for sensitive data
*/}}
{{- if or .Values.secrets.create .Values.notification.slack.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeguardian.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeguardian.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.notification.slack.enabled }}
  {{- if .Values.secrets.slackToken }}
  slack-token: {{ .Values.secrets.slackToken | b64enc }}
  {{- end }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.additionalSecrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
